// ─────────────────────────────────────────────────────────────────────────────
// URL-keying scheme
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @summary The synthetic URL namespace prefix used as the scheme for all
 * cache entry request URLs.
 *
 * @description
 * `CacheKeyNamespace` is the scheme and authority segment of every synthetic
 * URL generated by {@link canonicalKeyToURL}. Because the Cache API requires
 * `Request` objects as keys — and `Request` objects require valid URLs — every
 * canonical key must be embedded inside a fabricated URL that the browser
 * will accept.
 *
 * The namespace is intentionally unique and human-readable so that manual
 * DevTools inspection of the cache bucket clearly identifies entries as
 * belonging to this storage subsystem rather than genuine network resources.
 *
 * This is a module-level constant used exclusively inside this backend module.
 * It does not leak into the `IStorageBackend` contract.
 *
 * @example Inspecting the synthetic URL shape
 * ```ts
 * // For a canonical key: 'myapp:chrome:130:auth:user-session'
 * // The generated URL is:
 * 'https://storage.internal/myapp:chrome:130:auth:user-session'
 * //        ^^^^^^^^^^^^^^^^  ← CacheKeyNamespace
 * ```
 *
 * @see {@link canonicalKeyToURL} for the full URL-building logic.
 * @see {@link urlToCanonicalKey} for the inverse extraction logic.
 */
export const CACHE_KEY_NAMESPACE = 'https://storage.internal';

// ─────────────────────────────────────────────────────────────────────────────
// Custom response header names
// ─────────────────────────────────────────────────────────────────────────────

/** Monotonically increasing schema version — mirrors `StorageEnvelope.schema_version`. */
export const HDR_SCHEMA_VERSION = 'x-storage-schema-version';
/** Unix ms write timestamp — mirrors `StorageEnvelope.written_at`. */
export const HDR_WRITTEN_AT = 'x-storage-written-at';
/**
 * Unix ms expiry timestamp. The sentinel value `'-1'` means no expiry
 * (mirrors `StorageEnvelope.expires_at === null`).
 */
export const HDR_EXPIRES_AT = 'x-storage-expires-at';
/** User-defined eviction weight — mirrors `StorageEnvelope.weight`. */
export const HDR_WEIGHT = 'x-storage-weight';
/** The {@link BackendKind} string — always `'cache'` for this backend. */
export const HDR_BACKEND = 'x-storage-backend';
